import type { Article } from './types';

const article: Article = {
  slug: 'beginners-guide-to-juicing',
  title: "Beginner's Guide to Juicing: What You Need and How to Start",
  description: "New to juicing? Here's exactly what to buy, what to juice first, and how to get a good result every time. No fluff — just what works.",
  publishedAt: '2026-03-06',
  heroImage: 'https://images.unsplash.com/photo-1676831048336-9f05832937b0?w=800&q=80&fit=crop',
  heroAlt: 'Person pouring fresh orange juice into a blender',
  heroPhotographer: {
    name: 'Lorenzo Tomassetti',
    url: 'https://unsplash.com/@lorenzotomassetti',
  },
  hook: "Starting to juice is simple. Getting a good result the first time is what most beginners miss. Here's the equipment, the ingredients, and the method — so you're not guessing on day one.",
  tags: ['Health & Nutrition', 'Kitchen Tools'],
  relatedRecipeSlugs: ['apple-carrot-ginger', 'cucumber-apple-mint', 'carrot-beet-apple'],
  relatedArticleSlugs: ['best-juicing-combinations-for-beginners', 'what-to-grab-from-the-produce-aisle'],
  sections: [
    { type: 'h2', text: 'Do You Actually Need a Juicer?' },
    { type: 'body', text: 'Yes, if you want real juice. Blenders make smoothies — thick, fiber-heavy drinks where the pulp stays in. Juicers extract liquid and leave the fiber behind. The result is thinner, more concentrated, and easier to drink in volume.' },
    { type: 'body', text: 'That said, not all juicers are the same.' },
    { type: 'h2', text: 'Centrifugal Juicers' },
    { type: 'body', text: "These are the most common and affordable. A spinning blade shreds produce and forces juice through a mesh filter. They're fast and easy to clean — you can have a juice ready in under two minutes. The trade-off: the spinning generates heat, which can degrade some nutrients. The juice also oxidizes quickly, so it's best to drink it right away. Good for: beginners, everyday use, budget-conscious buyers. Price range: $60–$200." },
    { type: 'h2', text: 'Masticating (Cold Press) Juicers' },
    { type: 'body', text: "These crush and press produce slowly, generating little to no heat. The juice retains more nutrients and stays fresh longer — up to 72 hours in a sealed container. The trade-off: they're slower, harder to clean, and significantly more expensive. Good for: daily juicers who want maximum quality, leafy greens (spinach, kale, wheatgrass). Price range: $150–$500+." },
    { type: 'tip', text: 'Recommendation for beginners: Start with a centrifugal juicer. Learn what you like, build the habit, then upgrade if you want to.' },
    { type: 'h2', text: 'What to Buy at the Store' },
    { type: 'body', text: "You don't need a lot to start. The following ingredients are cheap, widely available, and produce consistent, good-tasting juice." },
    { type: 'h2', text: 'The Four Beginner Staples' },
    { type: 'body', text: "Apples — the best natural sweetener in juicing. One or two apples balance out almost any bitter or earthy vegetable. Always include one if you're adding greens. Carrots — sweet, high-yield, easy to juice. They pair with nearly everything and form the base of dozens of classic combinations. Cucumber — mostly water, which makes it a high-volume, mild-tasting base. It stretches your juice without adding much flavor. Ginger — a small knob (about an inch) adds a clean, sharp kick. It also helps with digestion and reduces inflammation. Don't skip it once you've tried it." },
    { type: 'tip', text: 'Add these once you\'re comfortable: celery (gut health), beets (earthy and sweet), kale or spinach (nutrient-dense — balance with apple), lemon (brightens any combination), turmeric (anti-inflammatory, pairs well with carrot and ginger).' },
    { type: 'h2', text: 'Your First Three Recipes' },
    { type: 'body', text: 'These are straightforward, forgiving, and work in any centrifugal juicer.' },
    { type: 'recipe', slug: 'apple-carrot-ginger', title: 'Apple Carrot Ginger Juice', description: 'The most reliable beginner recipe. Sweet, slightly spicy, no bitterness. Yields ~12–14 oz.' },
    { type: 'recipe', slug: 'cucumber-apple-mint', title: 'Cucumber Apple Mint Juice', description: 'Light and refreshing. Good as a morning juice or afternoon pick-me-up. Yields ~14–16 oz.' },
    { type: 'recipe', slug: 'carrot-beet-apple', title: 'Carrot Beet Apple Juice', description: 'Slightly earthy, naturally sweet, high in nutrients. The color is striking. Yields ~12–14 oz.' },
    { type: 'tip', text: 'Got other ingredients on hand? Use the JuiceMe ingredient tool — enter what\'s in your kitchen and it shows you every recipe you can make right now.' },
    { type: 'h2', text: 'How to Actually Use Your Juicer' },
    { type: 'body', text: "Wash everything, even ingredients you're peeling. Remove pits from stone fruits — they can damage the blade. Leave the skin on apples, cucumbers, and most vegetables. Peel citrus fruits — the white pith makes juice bitter. Cut produce into pieces that fit your juicer's feed tube." },
    { type: 'h2', text: 'Order of Juicing' },
    { type: 'body', text: 'Run ingredients in this order: soft produce first (leafy greens, herbs, cucumber), then hard produce (carrots, beets, ginger), then finish with apple or citrus. The high water content of apple and citrus flushes remaining pulp through the machine and extracts every last bit of juice from the previous ingredients.' },
    { type: 'h2', text: 'Common Beginner Mistakes' },
    { type: 'body', text: "Making it too sweet. A good ratio is roughly 80% vegetables, 20% fruit. Juicing leafy greens in a centrifugal juicer without prep — roll them into a tight ball before feeding them in. Letting juice sit — drink within 15–30 minutes for maximum nutrition. Skipping the cleaning step — clean immediately after use, pulp dries fast. Starting with too many ingredients — three or four is enough." },
    { type: 'h2', text: 'What to Do With the Pulp' },
    { type: 'body', text: "Don't throw it away. Carrot pulp works in muffins and veggie burgers. Beet pulp can be added to brownie batter. Vegetable pulp can be dehydrated into crackers or composted. Apple pulp works in oatmeal or baked goods. If you're not using it immediately, freeze it." },
    { type: 'h2', text: 'A Simple Weekly Routine' },
    { type: 'body', text: "Two to four times per week is sustainable for most people. Sunday: buy produce in bulk (carrots, apples, cucumbers, ginger stay fresh 5–7 days). Morning of: prep and juice in under 10 minutes with a centrifugal juicer. Immediately after: clean the juicer while you drink." },
    { type: 'tip', text: "The biggest reason people stop juicing is the cleanup. Keep the juicer on the counter, not stored away — out of sight means out of routine." },
    { type: 'h2', text: 'What to Try Next' },
    { type: 'body', text: "Once you've made the first three recipes a few times, start experimenting. The best way to build a juice habit is to work with what you already have at home rather than buying specific ingredients for each recipe. Enter your ingredients on JuiceMe and find every juice recipe you can make from them. No substitutions required." },
  ],
};

export default article;
